repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
      - id: trailing-whitespace
        exclude: ^texts/.*\.txt$
      - id: end-of-file-fixer
        exclude: ^texts/.*\.txt$
      - id: check-yaml
      - id: check-added-large-files

  - repo: https://github.com/psf/black
    rev: 23.3.0
    hooks:
      - id: black
        args: [--config=pyproject.toml]
        types: [ python ]

  - repo: https://github.com/pycqa/isort
    rev: 5.12.0
    hooks:
      - id: isort
        args: [--settings-file=pyproject.toml]
        types: [ python ]

  - repo: https://github.com/pycqa/flake8
    rev: 6.0.0
    hooks:
      - id: flake8
        entry: pflake8
        additional_dependencies: [ pyproject-flake8 ]
        types: [ python ]

  - repo: local
    hooks:
      - id: commit-message-lint
        name: commit-message-lint
        entry: python -m src.utils.commit_lint
        language: system
        stages: [commit-msg]
        always_run: true
        args:
          - check commit message
