[tool.flake8]
max-line-length = 100
extend-ignore = "E203" # Ignore whitespace before a colon

[tool.isort]
profile = "black"
line_length = 100
multi_line_output = 3
include_trailing_comma = true
force_grid_wrap = 0
use_parentheses = true
ensure_newline_before_comments = true

[tool.black]
line-length = 100
